import asyncio
import json
from datetime import datetime, timezone
from fastapi import APIRouter, HTTPException, Query, Request
from fastapi.responses import StreamingResponse
from pymongo.errors import PyMongoError
from bson import ObjectId

from database import db

router = APIRouter(prefix="/api", tags=["Network"])


def serialize(doc):
    doc = dict(doc)  # Fix: copy so we don't mutate the original
    doc["_id"] = str(doc["_id"])
    for key, value in doc.items():
        if isinstance(value, ObjectId): # This is for any "ObjectId" fields, especially of those generated by mongoDB
            doc[key] = str(value)
        # Convert ANY datetime to an ISO format string
        elif isinstance(value, datetime):
            doc[key] = value.isoformat()
    return doc


@router.get("/devices")
async def get_devices():
    try:
        hostnames = (
            db.alerts.distinct("hostname")
            + db.network_logs.distinct("hostname")
            + db.predictions.distinct("hostname")
        )
        unique_hostnames = sorted({h for h in hostnames if h and str(h).strip()})
        return {"devices": unique_hostnames, "count": len(unique_hostnames)}
    except PyMongoError as e:
        raise HTTPException(status_code=500, detail=f"MongoDB error: {str(e)}")


@router.get("/network/stream")
async def stream_network_logs(request: Request, hostname: str = Query(default=None)):
    async def event_generator():
        last_id = None

        while True:
            # Fix: detect client disconnect and stop the loop
            if await request.is_disconnected():
                break

            try:
                query = {}
                if hostname:
                    query["hostname"] = hostname
                if last_id:
                    query["_id"] = {"$gt": last_id}

                logs = list(
                    db.predictions.find(query).sort("timestamp", -1).limit(20)
                )

                if logs:
                    last_id = logs[-1]["_id"]
                    payload = [serialize(log) for log in logs]
                    yield f"data: {json.dumps(payload)}\n\n"

                await asyncio.sleep(3)

            except Exception as e:
                yield f"data: {json.dumps({'error': str(e)})}\n\n"
                await asyncio.sleep(5)

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )


@router.post("/logs")
async def receive_logs(request: Request):
    try:
        data = await request.json()
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid JSON")

    if isinstance(data, dict):
        logs = [data]
    elif isinstance(data, list):
        logs = data
    else:
        raise HTTPException(status_code=400, detail="Invalid format")

    try:
        for log in logs:
            log["received_at"] = datetime.now(timezone.utc)
            log["processed"] = False

        result = db.network_logs.insert_many(logs)
        return {
            "status": "logs stored",
            "count": len(result.inserted_ids),
        }

    except PyMongoError as e:
        raise HTTPException(status_code=500, detail=f"MongoDB insert failed: {str(e)}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Server error: {str(e)}")


@router.get("/network/logs")
def get_logs(limit: int = 50):
    try:
        logs = list(db.predictions.find().sort("timestamp", -1).limit(limit))
        return [serialize(log) for log in logs]
    except PyMongoError as e:
        raise HTTPException(status_code=500, detail=f"MongoDB error: {str(e)}")