services:
  mongodb:
    image: mongo:4.4.29
    ports:
      - "27017:27017" 
    # extra_hosts allows containers to resolve the host machine's gateway
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./ml_training:/ml_training  # This "injects" the folder into the container
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - ML_DATA_PATH=/ml_training/unsw/UNSW_NB15_testing-set.csv
      # Use the service name 'mongodb' so the backend can find the DB
      - MONGO_URI=mongodb://mongodb:27017/siem_db
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

# Persistence ensures your logs stay saved even if you restart the containers
volumes:
  mongo_data:
