# Use the latest Kali Linux image
FROM kalilinux/kali-rolling:latest

USER root

# Prevent interactive prompts
ENV DEBIAN_FRONTEND=noninteractive


# Use the official Kali rolling repository format
RUN echo "deb http://mirrors.esto.network/kali kali-rolling main contrib non-free non-free-firmware" > /etc/apt/sources.list

# # Install required tools
RUN apt-get -o Acquire::ForceIPv4=true update && \
    apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-full \
    iproute2 \
    iputils-ping \
    net-tools \
    hping3 \
    hydra \
    nmap \
    libcap2-bin \
    ca-certificates \
    dnsutils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /home/attacker

# Copy the script and supporting files
COPY user.txt rockyou.txt attack.py ./

# Optional Python dependency example
RUN pip3 install --break-system-packages boofuzz 

# Give packet tools capabilities inside the image
RUN setcap 'cap_net_raw,cap_net_admin+eip' "$(readlink -f /usr/sbin/hping3)" && \
    setcap 'cap_net_raw,cap_net_admin+eip' "$(readlink -f /usr/bin/nmap)"

# Stay as root for raw socket tools
USER root

CMD ["bash"]
